name: pray_quiet
description: "Embrace peaceful worship with PrayQuiet. Silence your phone while praying, make sure you phone is silent when its time to pray."

publish_to: 'none'

version: 1.0.5+20

environment:
  sdk: '>=3.0.5 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  native_device_timezone:
    git:
      url: https://github.com/codeswot/native_device_timezone.git
  do_not_disturb:
    git:
      url: https://github.com/codeswot/do_not_disturb.git
  flutter_riverpod: ^2.3.6
  lottie: ^2.4.0
  http: ^1.1.0
  shimmer: ^3.0.0
  geolocator: ^9.0.2
  geocoding: ^2.1.0
  shared_preferences: ^2.2.0
  riverpod_annotation: ^2.1.1
  flutter_animate: ^4.2.0
  logger: ^1.4.0
  url_launcher: ^6.1.12
  intl: any
  hijri: ^3.0.0
  flutter_local_notifications: ^15.1.0+1
  timezone: ^0.9.2
  android_alarm_manager_plus: ^3.0.1
  permission_handler: ^10.4.3
  flutter_screenutil: ^5.8.4
  package_info_plus: ^4.0.2
  flutter_volume_controller: ^1.2.7
  adhan_dart: ^1.0.8
  sound_mode: ^2.0.2
  pray_times: ^0.0.1
  flutter_native_splash: ^2.3.1
  flutter_localization: ^0.1.13
  adaptive_theme: ^3.3.0
  
  


dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^2.0.0
  rename: ^2.1.1
  build_runner: ^2.4.6
  riverpod_generator: ^2.2.3
  riverpod_lint: ^1.3.2
  drift_dev: ^2.10.0
  flutter_launcher_icons: ^0.13.1
flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/images/
    - assets/lottie/
    - assets/audio/

  fonts:
    - family: Nunito
      fonts:
        - asset: assets/fonts/nunito.ttf

